import { 
  ProductScore, 
  ProductTopicScore, 
  AISummary, 
  Mention 
} from '../../src/types/index.js';

export const productScoresCatalog: ProductScore[] = [
  // Phones
  {
    productId: 'prod-iphone-16-pro',
    overallScore: 9.1,
    confidenceScore: 94,
    positiveRatio: 82,
    neutralRatio: 11,
    negativeRatio: 7,
    mentionCount: 3420,
    sourceCount: 7,
    verdict: 'ALINIR',
    verdictReason: 'Kamera performansı, pil ömründeki iyileşme ve malzeme kalitesi kullanıcılar tarafından güçlü bir şekilde övülüyor. Fiyat yüksekliği dışında belirgin bir kronik kusur yok.',
    lastCalculatedAt: '2025-02-15T14:30:00Z'
  },
  {
    productId: 'prod-s24-ultra',
    overallScore: 8.9,
    confidenceScore: 92,
    positiveRatio: 79,
    neutralRatio: 13,
    negativeRatio: 8,
    mentionCount: 2890,
    sourceCount: 7,
    verdict: 'ALINIR',
    verdictReason: 'Yansıma önleyici ekranı, S Pen yetenekleri ve zoom kamerası çok beğeniliyor. Bazı kullanıcılar büyük ve köşeli kasayı tek elle kullanımda hantal buluyor.',
    lastCalculatedAt: '2025-02-14T09:15:00Z'
  },
  {
    productId: 'prod-iphone-15',
    overallScore: 8.8,
    confidenceScore: 93,
    positiveRatio: 80,
    neutralRatio: 12,
    negativeRatio: 8,
    mentionCount: 4100,
    sourceCount: 7,
    verdict: 'ALINIR',
    verdictReason: 'Dynamic Island ve 48MP ana kamera ile baz model olarak çok dengeli bir yükseltme. 60Hz ekran tazeleme hızı fiyatına göre en çok eleştirilen yönü.',
    lastCalculatedAt: '2025-02-10T12:00:00Z'
  },
  {
    productId: 'prod-xiaomi-14-ultra',
    overallScore: 9.2,
    confidenceScore: 89,
    positiveRatio: 84,
    neutralRatio: 10,
    negativeRatio: 6,
    mentionCount: 1650,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: '1 inçlik ana sensör ve Leica renk kalibrasyonu ile mobil fotoğrafçılıkta zirve noktası. Kamera çıkıntısının büyüklüğü elde tutuşu etkileyebiliyor.',
    lastCalculatedAt: '2025-02-11T16:00:00Z'
  },
  {
    productId: 'prod-samsung-a55',
    overallScore: 8.7,
    confidenceScore: 95,
    positiveRatio: 83,
    neutralRatio: 11,
    negativeRatio: 6,
    mentionCount: 5400,
    sourceCount: 7,
    verdict: 'ALINIR',
    verdictReason: 'Metal çerçevesi, uzun pil ömrü, 4 yıl Android güncelleme garantisi ve dengeli fiyatı ile 20.000 TL bandının en çok önerilen telefonu.',
    lastCalculatedAt: '2025-02-14T15:30:00Z'
  },
  {
    productId: 'prod-poco-x6-pro',
    overallScore: 8.6,
    confidenceScore: 91,
    positiveRatio: 78,
    neutralRatio: 12,
    negativeRatio: 10,
    mentionCount: 3200,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Fiyatına göre olağanüstü işlemci gücü ve akıcı ekran. Plastik arka kapak hissiyatı ve kamera performansının ortalama kalması göze çarpan eksileri.',
    lastCalculatedAt: '2025-02-12T10:00:00Z'
  },

  // Laptops
  {
    productId: 'prod-macbook-air-m3',
    overallScore: 9.3,
    confidenceScore: 95,
    positiveRatio: 88,
    neutralRatio: 8,
    negativeRatio: 4,
    mentionCount: 1840,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Göz alıcı pil dayanımı, sıfır fan gürültüsü ve üstün klavye/touchpad deneyimiyle segmentinin en çok tavsiye edilen dizüstü bilgisayarı.',
    lastCalculatedAt: '2025-02-10T11:00:00Z'
  },
  {
    productId: 'prod-macbook-pro-14-m3',
    overallScore: 9.5,
    confidenceScore: 94,
    positiveRatio: 90,
    neutralRatio: 7,
    negativeRatio: 3,
    mentionCount: 1420,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Liquid Retina XDR ekran parlaklığı, 120Hz ProMotion akıcılığı, HDMI/SD kart yuvaları ve termal performansı ile profesyonellerin ortak tercihi.',
    lastCalculatedAt: '2025-02-12T18:00:00Z'
  },
  {
    productId: 'prod-asus-zephyrus-g14',
    overallScore: 9.0,
    confidenceScore: 90,
    positiveRatio: 82,
    neutralRatio: 11,
    negativeRatio: 7,
    mentionCount: 1180,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: '3K 120Hz OLED ekranı, hafif CNC alüminyum kasası ve RTX 4070 gücüyle hem iş hem oyun için en şık Windows dizüstü modeli.',
    lastCalculatedAt: '2025-02-14T09:00:00Z'
  },
  {
    productId: 'prod-lenovo-legion-pro-5',
    overallScore: 8.9,
    confidenceScore: 92,
    positiveRatio: 81,
    neutralRatio: 12,
    negativeRatio: 7,
    mentionCount: 1950,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: '140W tam güç RTX 4070, üstün ColdFront soğutma ve 240Hz ekranıyla saf oyuncular için kusursuz fiyat/güç dengesi sunuyor.',
    lastCalculatedAt: '2025-02-09T14:20:00Z'
  },
  {
    productId: 'prod-huawei-matebook-d16',
    overallScore: 8.7,
    confidenceScore: 91,
    positiveRatio: 80,
    neutralRatio: 13,
    negativeRatio: 7,
    mentionCount: 2200,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'i9 işlemci performansı, 16 inç geniş ekranı ve hafif gövdesiyle ofis ve mühendislik öğrencileri için çok cazip fiyat/performans paketi.',
    lastCalculatedAt: '2025-02-08T11:45:00Z'
  },

  // Audio
  {
    productId: 'prod-sony-wh1000xm5',
    overallScore: 9.0,
    confidenceScore: 91,
    positiveRatio: 81,
    neutralRatio: 12,
    negativeRatio: 7,
    mentionCount: 2340,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Uçak ve ofis ortamlarında en iyi aktif gürültü engelleme performansına sahip. Katlanamayan gövde yapısı taşımada önceki nesle göre eleştiri almış.',
    lastCalculatedAt: '2025-02-12T16:45:00Z'
  },
  {
    productId: 'prod-airpods-pro-2',
    overallScore: 9.2,
    confidenceScore: 96,
    positiveRatio: 86,
    neutralRatio: 9,
    negativeRatio: 5,
    mentionCount: 5120,
    sourceCount: 7,
    verdict: 'ALINIR',
    verdictReason: 'Apple ekosistemindeki kusursuz geçiş, sınıfının lideri şeffaf mod ve adaptif ses kontrolü ile en yüksek kullanıcı memnuniyeti oranına sahip.',
    lastCalculatedAt: '2025-02-14T11:40:00Z'
  },
  {
    productId: 'prod-bose-qc-ultra',
    overallScore: 9.1,
    confidenceScore: 89,
    positiveRatio: 83,
    neutralRatio: 11,
    negativeRatio: 6,
    mentionCount: 1350,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Katlanabilir ergonomisi, kafa yapısına baskı yapmayan lüks yastıkları ve derin ANC performansı ile seyahat edenlerin 1 numaralı tercihi.',
    lastCalculatedAt: '2025-02-13T10:15:00Z'
  },
  {
    productId: 'prod-sennheiser-momentum-4',
    overallScore: 9.0,
    confidenceScore: 88,
    positiveRatio: 84,
    neutralRatio: 10,
    negativeRatio: 6,
    mentionCount: 1480,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: '60 saatlik akıl almaz pil ömrü ve odyofil kalitesinde doğal ses sahnesi ile müzik tutkunlarını mest ediyor.',
    lastCalculatedAt: '2025-02-07T12:00:00Z'
  },
  {
    productId: 'prod-anker-liberty-4-nc',
    overallScore: 8.9,
    confidenceScore: 94,
    positiveRatio: 85,
    neutralRatio: 9,
    negativeRatio: 6,
    mentionCount: 3800,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: '3.000 TL altına amiral gemisi kulaklıkların ANC performansını ve LDAC desteğini getiren en popüler F/P kulaklık.',
    lastCalculatedAt: '2025-02-14T17:00:00Z'
  },
  {
    productId: 'prod-jbl-flip-6',
    overallScore: 8.8,
    confidenceScore: 93,
    positiveRatio: 84,
    neutralRatio: 10,
    negativeRatio: 6,
    mentionCount: 2900,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Kompakt boyutuna göre şaşırtıcı bas gücü, suya/toza tam dayanıklılık ve piknik/plaj kullanımında yüksek sağlamlık.',
    lastCalculatedAt: '2025-02-05T14:30:00Z'
  },

  // Robot Vacuums
  {
    productId: 'prod-roborock-s8-pro',
    overallScore: 9.1,
    confidenceScore: 90,
    positiveRatio: 84,
    neutralRatio: 10,
    negativeRatio: 6,
    mentionCount: 2110,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Paspas yıkama ve sıcak hava kurutma istasyonu temizlik iş yükünü sıfıra indiriyor. Çift fırça sistemi saç dolanmasını büyük ölçüde engelliyor.',
    lastCalculatedAt: '2025-02-08T18:20:00Z'
  },
  {
    productId: 'prod-dreame-l20-ultra',
    overallScore: 9.2,
    confidenceScore: 89,
    positiveRatio: 85,
    neutralRatio: 9,
    negativeRatio: 6,
    mentionCount: 1620,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Dışa doğru uzayan MopExtend paspas kolu ile süpürgelik kenarlarında sıfır boşluk bırakıyor. 7000 Pa emiş gücü ve kamera zekası mükemmel.',
    lastCalculatedAt: '2025-02-14T09:40:00Z'
  },
  {
    productId: 'prod-roborock-q-revo',
    overallScore: 9.0,
    confidenceScore: 92,
    positiveRatio: 83,
    neutralRatio: 11,
    negativeRatio: 6,
    mentionCount: 2450,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Çift döner paspas sistemi ve tam otomatik istasyonu ile S8 Pro\'nun sunduğu konforu 15.000 TL daha uyguna veren F/P robot şampiyonu.',
    lastCalculatedAt: '2025-02-13T12:00:00Z'
  },
  {
    productId: 'prod-xiaomi-x20-plus',
    overallScore: 8.8,
    confidenceScore: 93,
    positiveRatio: 81,
    neutralRatio: 12,
    negativeRatio: 7,
    mentionCount: 2800,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: '20.000 TL civarı fiyatıyla hem paspas yıkayan hem toz boşaltan istasyon sunması inanılmaz bir popülerlik sağladı.',
    lastCalculatedAt: '2025-02-15T08:30:00Z'
  },

  // Home Appliances
  {
    productId: 'prod-dyson-v15',
    overallScore: 8.8,
    confidenceScore: 93,
    positiveRatio: 77,
    neutralRatio: 12,
    negativeRatio: 11,
    mentionCount: 3820,
    sourceCount: 7,
    verdict: 'ALINIR',
    verdictReason: 'Lazerli başlığın görünmeyen tozları göstermesi ve çekim gücü mükemmel. Gövdenin biraz ağır olması ve sürekli tetiğe basma ihtiyacı bazı kullanıcıları yorabiliyor.',
    lastCalculatedAt: '2025-02-15T12:00:00Z'
  },
  {
    productId: 'prod-airfryer-xxl',
    overallScore: 8.5,
    confidenceScore: 94,
    positiveRatio: 74,
    neutralRatio: 15,
    negativeRatio: 11,
    mentionCount: 4780,
    sourceCount: 7,
    verdict: 'ALINIR',
    verdictReason: 'Hızlı pişirme ve çıtır sonuçlar tam puan alıyor. Hazne temizliğinin ve teflon kaplamanın uzun vadede hassas kullanılması gerektiği vurgulanıyor.',
    lastCalculatedAt: '2025-02-11T10:00:00Z'
  },
  {
    productId: 'prod-dyson-airwrap',
    overallScore: 9.0,
    confidenceScore: 92,
    positiveRatio: 82,
    neutralRatio: 10,
    negativeRatio: 8,
    mentionCount: 4200,
    sourceCount: 7,
    verdict: 'ALINIR',
    verdictReason: 'Saçı yakmadan Coanda etkisiyle kuaför fönü kalitesinde dalga yapması en çok övülen özelliği. Fiyatının yüksekliği ve ilk haftalarda el alışkanlığı istemesi tek eksiği.',
    lastCalculatedAt: '2025-02-14T13:00:00Z'
  },
  {
    productId: 'prod-delonghi-magnifica-s',
    overallScore: 9.2,
    confidenceScore: 95,
    positiveRatio: 87,
    neutralRatio: 8,
    negativeRatio: 5,
    mentionCount: 3100,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Çekirdek kahveyi taze öğütüp mükemmel krema ile vermesi, bozulmayan mekanik aksamı ve kolay temizliği ile ev baristalarının vazgeçilmezi.',
    lastCalculatedAt: '2025-02-10T16:15:00Z'
  },
  {
    productId: 'prod-tefal-optigrill',
    overallScore: 8.7,
    confidenceScore: 90,
    positiveRatio: 79,
    neutralRatio: 13,
    negativeRatio: 8,
    mentionCount: 1900,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Etin pişme derecesini renkli göstergeyle haber vermesi ve sulu bırakması harika. Çıkarılabilir döküm plakaların bulaşık makinesinde yıkanabilmesi büyük konfor.',
    lastCalculatedAt: '2025-02-06T11:00:00Z'
  },

  // Smartwatches
  {
    productId: 'prod-apple-watch-ultra-2',
    overallScore: 9.3,
    confidenceScore: 92,
    positiveRatio: 86,
    neutralRatio: 9,
    negativeRatio: 5,
    mentionCount: 1750,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: '3000 nit ultra parlak ekran, çizilmez titanyum kasa, hassas dalış/outdoor sensörleri ve 3 güne varan pil ömrüyle Apple ekosisteminin zirvesi.',
    lastCalculatedAt: '2025-02-15T15:00:00Z'
  },
  {
    productId: 'prod-apple-watch-series-10',
    overallScore: 9.0,
    confidenceScore: 91,
    positiveRatio: 82,
    neutralRatio: 11,
    negativeRatio: 7,
    mentionCount: 2600,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Gözle görülür incelen kasası ve geniş açılı OLED ekranı bilekte çok zarif duruyor. 1-1.5 günlük klasik pil süresi hala her gün şarj gerektiriyor.',
    lastCalculatedAt: '2025-02-14T10:20:00Z'
  },
  {
    productId: 'prod-samsung-watch-7',
    overallScore: 8.7,
    confidenceScore: 90,
    positiveRatio: 78,
    neutralRatio: 14,
    negativeRatio: 8,
    mentionCount: 2100,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: 'Yeni 3nm işlemciyle menü geçişleri yağ gibi akıcı. Çift frekanslı GPS koşu rotalarında çok başarılı, ancak pil ömrü 1.5 gün ile sınırlı.',
    lastCalculatedAt: '2025-02-12T13:30:00Z'
  },
  {
    productId: 'prod-huawei-watch-gt-4',
    overallScore: 9.1,
    confidenceScore: 94,
    positiveRatio: 87,
    neutralRatio: 8,
    negativeRatio: 5,
    mentionCount: 3900,
    sourceCount: 7,
    verdict: 'ALINIR',
    verdictReason: 'Klasik lüks saat görünümü, 10-14 gün süren şarjı ve hem iPhone hem Android ile sorunsuz çalışmasıyla en yüksek kullanıcı memnuniyetine sahip saat.',
    lastCalculatedAt: '2025-02-13T16:00:00Z'
  },
  {
    productId: 'prod-garmin-fenix-7-pro',
    overallScore: 9.4,
    confidenceScore: 88,
    positiveRatio: 89,
    neutralRatio: 8,
    negativeRatio: 3,
    mentionCount: 920,
    sourceCount: 5,
    verdict: 'ALINIR',
    verdictReason: 'Güneş enerjisi şarjı, dahili LED feneri, internetsiz topoğrafik haritaları ve sonsuz antrenman verisiyle profesyonel sporcular için rakipsiz.',
    lastCalculatedAt: '2025-02-05T09:00:00Z'
  },

  // TVs
  {
    productId: 'prod-lg-c4-oled',
    overallScore: 9.2,
    confidenceScore: 88,
    positiveRatio: 85,
    neutralRatio: 10,
    negativeRatio: 5,
    mentionCount: 1250,
    sourceCount: 5,
    verdict: 'ALINIR',
    verdictReason: 'Kusursuz kontrast ve 144Hz oyun modu ile hem sinema hem PS5 kullanıcıları için referans TV konumunda.',
    lastCalculatedAt: '2025-02-05T13:10:00Z'
  },
  {
    productId: 'prod-samsung-qn90d',
    overallScore: 9.1,
    confidenceScore: 89,
    positiveRatio: 83,
    neutralRatio: 11,
    negativeRatio: 6,
    mentionCount: 1100,
    sourceCount: 5,
    verdict: 'ALINIR',
    verdictReason: 'Çok aydınlık salonlarda dahi parlamayan mat kaplaması ve 2000 nit patlayıcı HDR parlaklığı ile gündüz TV izleyenler için en iyi seçenek.',
    lastCalculatedAt: '2025-02-11T14:00:00Z'
  },
  {
    productId: 'prod-tcl-55c755',
    overallScore: 8.9,
    confidenceScore: 91,
    positiveRatio: 82,
    neutralRatio: 12,
    negativeRatio: 6,
    mentionCount: 1850,
    sourceCount: 6,
    verdict: 'ALINIR',
    verdictReason: '500+ karartma bölgeli Mini-LED paneli, 144Hz oyun desteği ve Onkyo dahili subwoofer ses sistemiyle 35.000 TL bandının tartışmasız F/P kralı.',
    lastCalculatedAt: '2025-02-14T12:00:00Z'
  }
];
